---
- hosts: all
  become: yes
  tasks:
    # - name: list web servers
    #   debug:
    #     msg: "web servers are {{ groups['web']['ansible_host']|join(' ') }}"
    - name: Display IP addresses of 'web'
      debug:
        msg: "IP addresses in 'web': {{ groups['web'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list | join(' ') }}"

    - name: Create directory for template deployment
      file:
        path: /home/ansible/lab-templates
        state: directory
        mode: '0755'
    
    - name: Deploy sudo template
      template:
        src: hardened.j2
        dest: /etc/sudoers.d/hardened
        mode: '0440'
        # validate: /sbin/visudo -cf %s
    
    - name: Display success message
      debug:
        msg: "Hardened sudoers template deployed successfully"